import Image from "next/image";
import Link from "next/link";
import styles from "./page.module.css"


async function getData(){
    const res = await fetch('https://dummyjson.com/products')
    if(!res.ok){
        throw new Error('Failed to fetch')
    }
    return res.json()
}

export const metadata = {
    title: ' Kanzmarket - Products ',
    description: 'Generated by create next app',
  }

export default async function blog() {
    const data=await getData()
    const products =data.products
    return (
          
        <div className={styles.mainContainer}>
            {
                products.map(p=>(
                    <Link href={`/Blog/${p.id}`} key={p.id} className={styles.post}>
                        <div className={styles.imageContainer}>
                            <Image
                            className={styles.image}
                            src={p.thumbnail}
                            width={350}
                            height={250}
                            alt="post image" 
                            />
                        </div>
                            <div className={styles.content}>
                                <h1 className={styles.title}>{p.title}</h1>
                                <p className={styles.text}>{p.description}</p>
                            </div>
                
            </Link>
                ))
            }
           
        </div>
      
    )
  }