
export const metadata = {
  title: ' Kanzmarket - Contact ',
  description: 'Generated by create next app',
}
import React from 'react'

export default function contact() {
  return (
    <h1>contact</h1>
  )
}
