export const metadata = {
  title: ' Kanzmarket - About ',
  description: 'Generated by create next app',
}

export default function about() {
    return (
    <div>
      <h1>About</h1>
    </div>
      
    )
  }