import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar/Navbar'
import Footer from '@/components/Footer/Footer'
import { Montserrat } from 'next/font/google'
import { ThemeContext ,ThemeProvider } from '@/components/Context/Themecontext'

const bodyFont = Montserrat({
  subsets:['latin'],
  weight : ['400','700','900']
})
const inter = Inter({ 
  subsets: ['latin'],
 })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
     <body className={bodyFont.className}>
        <ThemeProvider>
        <div className="container">
        <Navbar/>
        {children}
        <Footer/>
        </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
