export const links =[
    {
        id:1,
        title:"About",
        url:"/About"
    },
    {
        id:2,
        title:"Portfolio",
        url:"/Portfolio"
    },{
        id:3,
        title:"Contact",
        url:"/Contact"
    },{
        id:4,
        title:"Blog",
        url:"/Blog"
    }
]