export const metadata = {
  title: ' Kanzmarket - Portfolio ',
  description: 'Generated by create next app',
}

export default function portfolio() {
    return (
      <div>
         <h1>Portfolio</h1>
      </div>
    )
  }